name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  server-ci:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./server
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          cache: 'poetry'
          cache-dependency-path: './server/poetry.lock'
      - name: Install Poetry
        run: pip install poetry
      - name: Install dependencies
        run: poetry install --no-root
      - name: Build Docker image
        run: docker build -t server-api .
      - name: Upload Server Artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: server-build-log
          path: ./server

  client-ci:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./client
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: './client/package-lock.json'
      - name: Install dependencies
        run: npm install
      - name: Build project
        run: npm run build
      - name: Build Docker image
        run: docker build -t client-ui .
      - name: Upload Client Dist
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: client-dist
          path: ./client/dist
